### ISSUE TITLE
Enable battery display

### ISSUE THREAD

**Issue by rricharz** [bcnjr5/linux-pitop-battery#4]
Add explanation on how to enable the battery panel item in the standard Raspbian Jessie gui

**Comment by bcnjr5** [comment]
This is going to take a while, as my current desktop environment is best described by the `~/.xsession` file:
```sh
xsettingsd &
eval $(< ~/.fehbg)
compton -b
tint2 &
wicd-gtk -t &
openbox
```

I will put (yet another) stock version of Raspbian on the unused 8GB card that came with the Pi-Top, but that always seems to take forever.

**Comment by rricharz** [comment]
No problem, I have an SD card ready and it's really a trivial task. I have added the instructions to Readme.md. Feel free to improve at your liking.

**Comment by bcnjr5** [comment]
Ah, thanks. :+1:
